version: '3'
services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - dbs:/var/lib/mysql
    env_file:
      - stack.env
    networks:
      - internal
      
  yourls:
    container_name: yourls
    #links:
    #  - db
    depends_on:
      - db
    ports:
      - 8080:80
    env_file:
      - stack.env
  
    image: yourls
    networks:
      - internal
      - proxy
    
volumes:
  dbs:
  
networks:
  internal:
  proxy:
    external: true