version: "3.3"

services:
  app:
    image: fireflyiii/core:latest
    hostname: firefly
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    #    ports:
    #      - 80:8080
    depends_on:
      - db
    networks:
      - internal
      - proxy
  db:
    image: mariadb
    restart: always
    env_file: .env
    volumes:
      - firefly_iii_db:/var/lib/mysql
    networks:
      - internal

volumes:
  firefly_iii_upload:
  firefly_iii_db:

networks:
  internal:
  proxy:
    external: true
