version: "3.3"

services:
  element:
    image: vectorim/element-web:latest
    restart: unless-stopped
    #      ports:
    #        - 8081:80
    hostname: element-matrix
    volumes:
      - ${PATH_TO_CONFIG}/element-config.json:/app/config.json:ro
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.${PROJECT_NAME}.tls=true"
      - "traefik.http.services.${PROJECT_NAME}-service.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
