version: "3"

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - internal

  app:
    image: nextcloud
    hostname: nextcloud
    restart: always
    volumes:
      - nextcloud:/var/www/html
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - internal
      - proxy

  redis:
    image: redis:alpine
    #    entrypoint: redis-server --appendonly yes
    restart: always
    depends_on:
      - db
    networks:
      - internal

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    networks:
      - internal

volumes:
  db:
  nextcloud:

networks:
  internal:
  proxy:
    external: true
