version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission
    hostname: transmission
    #   restart: unless-stopped
    container_name: transmission
    env_file:
      - .env
    ports:
      #      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=web"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.${PROJECT_NAME}.tls=false"
      - "traefik.http.services.${PROJECT_NAME}-service.loadbalancer.server.port=9091"

networks:
  default:
    external:
      name: proxy
