version: "2"
services:
  plex:
    container_name: plex
    hostname: plex
    image: plexinc/pms-docker
    #   restart: unless-stopped
    ports:
      #     - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    env_file:
      - .env
    volumes:
      - ${PATH_TO_CONFIG}:/config
      - ${PATH_TO_TRANSCODE}:/transcode
      - ${PATH_TO_MEDIA}:/data
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=web"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.${PROJECT_NAME}.tls=false"
      - "traefik.http.services.${PROJECT_NAME}-service.loadbalancer.server.port=32400"

networks:
  proxy:
    external: true
