version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
      - 25516:25516/udp # Simple Voice Chat plugin port
    env_file:
      - .env
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ${PATH_TO_DATA}:/data
